version: "3.4"
services:
  neko:
    image: "manlineroot12/virtualbrowser/v2"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8081:8081"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
    cap_add:
      - SYS_ADMIN
